import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { partialTotalMixups, readEvalResults, weakSpots, type EvalResultsFile } from "./ai-check";

const dir = mkdtempSync(join(tmpdir(), "ulat-ai-check-"));
afterAll(() => rmSync(dir, { recursive: true, force: true }));

const row = (none: number, partial: number, total: number, unclear = 0) => ({ none, partial, total, unclear });
const language = (notes: number, rate: number | null) => ({ notes, all_right_rate: rate });

/** The keys of eval/results.json the page reads, with one extra key the page does not know. */
function results(): EvalResultsFile & { warning: string } {
  return {
    warning: "Generated by pnpm eval. Never edit these numbers by hand. Run pnpm eval again instead.",
    generated_at: "2026-10-09T06:48:00.000Z",
    model: "gemma4:e4b",
    counts: { photos: { run: 40, scored: 30 }, voice: { run: 12 }, skipped: 0 },
    photos: {
      agreement: { n: 40, agreed: 30, rate: 0.75 },
      accuracy: { n: 30, correct: 24, rate: 0.8 },
      confusion_matrix: { none: row(10, 0, 0), partial: row(1, 8, 2), total: row(0, 3, 6) },
      seconds: { n: 40, mean: 5.2, median: 4.1 },
    },
    voice: {
      languages: {
        tl: language(3, 1),
        ceb: language(3, 0.5),
        mixed: language(3, 0.75),
        en: language(3, 1),
      },
    },
    battery: { percent_per_100_houses: 12.5, houses_per_full_charge: 800, reason: null },
  };
}

function write(name: string, content: string): string {
  const path = join(dir, name);
  writeFileSync(path, content);
  return path;
}

describe("readEvalResults", () => {
  it("reads a file that is there", async () => {
    const reading = await readEvalResults(write("present.json", JSON.stringify(results())));
    expect(reading.status).toBe("ok");
    if (reading.status === "ok") {
      expect(reading.results.photos.accuracy.rate).toBe(0.8);
      expect(reading.results.voice.languages.ceb.all_right_rate).toBe(0.5);
    }
  });

  it("drops keys the page does not show", async () => {
    const reading = await readEvalResults(write("extra.json", JSON.stringify(results())));
    expect(reading.status === "ok" && "warning" in reading.results).toBe(false);
  });

  it("keeps a rate that is null", async () => {
    const file = results();
    file.photos.accuracy = { n: 0, correct: 0, rate: null };
    file.battery = { percent_per_100_houses: null, houses_per_full_charge: null, reason: "The hub was on AC power." };
    const reading = await readEvalResults(write("nulls.json", JSON.stringify(file)));
    expect(reading.status).toBe("ok");
  });

  it("says missing when there is no file", async () => {
    expect(await readEvalResults(join(dir, "never-written.json"))).toEqual({ status: "missing" });
  });

  it("says invalid for a file that is not JSON", async () => {
    expect(await readEvalResults(write("broken.json", "{ half a file"))).toEqual({ status: "invalid", reason: "The file is not valid JSON." });
  });

  it("says invalid for an empty file", async () => {
    expect((await readEvalResults(write("empty.json", ""))).status).toBe("invalid");
  });

  it("says invalid, and where, for a key that is missing", async () => {
    const file: Record<string, unknown> = { ...results() };
    delete file.photos;
    expect(await readEvalResults(write("no-photos.json", JSON.stringify(file)))).toEqual({
      status: "invalid",
      reason: "The file does not have the expected shape at photos.",
    });
  });

  it("says invalid for a rate outside 0 to 1", async () => {
    const file = results();
    file.photos.accuracy.rate = 87;
    expect((await readEvalResults(write("big-rate.json", JSON.stringify(file)))).status).toBe("invalid");
  });

  it("says invalid for a date that is not a date", async () => {
    const file = { ...results(), generated_at: "last week" };
    expect((await readEvalResults(write("bad-date.json", JSON.stringify(file)))).status).toBe("invalid");
  });

  it("says invalid for JSON that is not an object", async () => {
    expect((await readEvalResults(write("array.json", "[]"))).status).toBe("invalid");
    expect((await readEvalResults(write("null.json", "null"))).status).toBe("invalid");
  });

  it("says invalid, and does not throw, when the path cannot be read as a file", async () => {
    const folder = join(dir, "a-folder");
    mkdirSync(folder);
    expect(await readEvalResults(folder)).toEqual({ status: "invalid", reason: "The file could not be read." });
  });
});

describe("weakSpots", () => {
  it("reports each thing the file shows", () => {
    const file = results();
    file.counts.skipped = 2;
    file.battery.reason = "The hub was on AC power, or the power source is unknown. Unplug it and run again.";
    file.photos.confusion_matrix.none.unclear = 1;
    expect(weakSpots(file)).toEqual([
      "Partial and total were mixed up on 5 photos.",
      "The AI said unclear on 1 photo.",
      "Bisaya notes were the weakest, 50% all right.",
      "2 items were left out of the scores.",
      "The hub was on AC power, or the power source is unknown. Unplug it and run again.",
    ]);
  });

  it("says so when nothing stood out", () => {
    const file = results();
    file.photos.confusion_matrix = { none: row(10, 0, 0), partial: row(0, 10, 0), total: row(0, 0, 10) };
    file.voice.languages = { tl: language(3, 1), ceb: language(3, 1), mixed: language(0, null), en: language(3, 1) };
    expect(weakSpots(file)).toEqual(["Nothing stood out in the last run."]);
  });

  it("counts partial and total mixed up in both directions", () => {
    expect(partialTotalMixups(results())).toBe(5);
  });
});
