/** App routes. See docs/SPEC.md section 2 and design/README.md. */
export const routes = {
  family: {
    home: "/",
    report: "/report",
    reportFamily: "/report?for=family",
    reportNeighbor: "/report?for=neighbor",
    check: "/report/check",
    location: "/report/location",
    sent: "/report/sent",
    status: (code?: string) => (code ? `/status?code=${code}` : "/status"),
    map: "/map",
    updates: "/updates",
    safe: "/safe",
    safeDone: "/safe/done",
  },
  responder: {
    signIn: "/r/sign-in",
    toVisit: "/r",
    map: "/r/map",
    done: "/r/done",
    queue: "/r/queue",
    report: (code: string) => `/r/reports/${code}`,
    newHouse: "/r/new",
    assess: (entryId: string) => `/r/assess/${entryId}`,
    confirmed: (entryId: string) => `/r/assess/${entryId}/confirmed`,
  },
  hub: {
    overview: "/hub",
    lock: "/hub/lock",
    review: "/hub/review",
    familyReports: "/hub/review/family-reports",
    duplicates: "/hub/review/duplicates",
    map: "/hub/map",
    mapAdd: "/hub/map/add",
    entries: "/hub/entries",
    entry: (id: string) => `/hub/entries/${id}`,
    reports: "/hub/reports",
    reportPrint: (n: number) => `/hub/reports/${n}/print`,
    updates: "/hub/updates",
    safeList: "/hub/safe-list",
    desk: "/hub/desk",
    setup: "/hub/setup",
    checklist: "/hub/checklist",
    aiCheck: "/hub/ai-check",
    poster: "/hub/poster",
  },
} as const;
